# This is an example of how to run the backend in production using secret files
# and using the image from GitHub Packages.

name: strecklista-backend

services:
    server:
        image: strecklista-backend
        container_name: strecklista-backend-server
        restart: always
        env_file: '.env'
        environment:
            - DATABASE_URL=postgresql://postgres:secret-dev-password@db:5432/strecklista

        ports:
            - '8080:8080'

        depends_on:
            db:
                condition: service_healthy
    db:
        image: postgres:18
        container_name: strecklista-backend-db
        restart: always
        user: postgres
        volumes:
            - db-data:/var/lib/postgresql
        environment:
            - POSTGRES_DB=strecklista
            - POSTGRES_PASSWORD=secret-dev-password
        expose:
            - 5432
        healthcheck:
            test: ['CMD', 'pg_isready']
            interval: 10s
            timeout: 5s
            retries: 5
volumes:
    db-data:
